# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa59a1cf3785170f99a5f3514939b673ff836f1aeb706827ddd93cbde77e8f4528fca2272a14325d133e6acdaf388f946d1d805847b2fbdd9ae1c7be58cb2baf

test:
  secret_key_base: 3a0b3091583c3e6dd3c427f3dbc3e1207b5551380e4973ae38e99aa33c2ad97dd75f6d7dd775bc07682b9a513cbe115619674aea0247ac2643ed29cad687a62a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
